### ISSUE TITLE
Use GitHub pages to provide an online version.

### ISSUE THREAD

**Issue by huonw** [fred-wang/AcidTestsMathML#1]
GitHub provides static hosting for projects via [GitHub Pages](http://pages.github.com/), this is perfect to host the various acid tests as they are being developed.

It is enough to just create a `gh-pages` branch and the tests will be available at `<username>.github.com/AcidTestsMathML/acid2` (or `acid3`). 

[Example](http://dbaupp.github.com/AcidTestsMathML/). (I just made the `gh-pages` branch, and then created a very basic top level `index.html` to act as a landing page. [diff](https://github.com/dbaupp/AcidTestsMathML/compare/master...gh-pages).)

Development could either happen entirely on the `gh-pages` branch, or just keep it rebased on top of `master`.

**Comment by fred-wang** [comment]
Thank you for the information. I've just created this gh-pages branch. Hopefully the pages will show up soon.

**Comment by huonw** [comment]
Yay! [It's up already](http://fred-wang.github.com/AcidTestsMathML/acid2/).

**Comment by fred-wang** [comment]
Great! Thanks again. I'm closing this bug now.
